"""Initial migration

Revision ID: ce603aecdfa2
Revises: 
Create Date: 2019-01-22 13:39:08.167517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce603aecdfa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('wechat_open_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('wechat_union_id', sa.String(length=255), nullable=True))
    op.drop_index('openid', table_name='user')
    op.create_unique_constraint(None, 'user', ['wechat_open_id'])
    op.drop_column('user', 'openid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('openid', mysql.VARCHAR(length=240), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('openid', 'user', ['openid'], unique=True)
    op.drop_column('user', 'wechat_union_id')
    op.drop_column('user', 'wechat_open_id')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
